// <auto-generated />
namespace Yourlake_Azure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTimeIdForDonneeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTimeIdForDonneeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201611301244485_addTimeIdForDonneeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
